/**
 * GraphQL Generated Types
 * =======================
 * This file is auto-generated by GraphQL Code Generator.
 * Run `npm run codegen` to regenerate.
 *
 * For now, this is a placeholder with manual type exports.
 * After running codegen, this file will be replaced with generated types.
 */

// Re-export types from queries.ts for convenience
export type {
  Image,
  Slug,
  File,
  Profile,
  Skill,
  SkillGroup,
  Tradeoff,
  TechnicalDecision,
  Challenge,
  CodeHighlight,
  Project,
  Experience,
  Education,
  Testimonial,
  Tag,
  CodeBlock,
  ChartData,
  KnowledgeNode,
  KnowledgeGraphNode,
  KnowledgeGraphEdge,
  KnowledgeGraph,
  LandingPageData,
} from '@/lib/graphql/queries';
