import {
  Logo,
  LogoProfessional,
  LogoCreative,
  LogoStreetwear,
  LogoTechy,
  LogoBridgeDJ,
  LogoSportsVinyl,
  LogoGoldenGateMinimal,
  LogoChampionshipRing,
  LogoBasketballVinyl,
  LogoNeonGlow,
  LogoRetro80s,
  LogoGeometric,
  LogoHolographic,
  LogoSticker,
  LogoMonogramShield,
  LogoCassette,
  LogoWaveform,
  LogoPixel,
  LogoStamp,
  LogoBlueprint,
  LogoMark,
  LogoGradientBurst,
  LogoOutline,
  LogoGlitch,
  LogoJerseyNumber,
  LogoVinylOnly,
  LogoTerminal,
  LogoHexagon,
  LogoSportsCard,
  LogoCoin,
  LogoGraffitiTag,
  LogoDJMixer,
  LogoBeatGrid,
  LogoFrequencySpectrum,
  LogoTurntablePlatter,
  LogoCDJDisplay,
  LogoScratchPattern,
  LogoSoundwaveCircle,
  LogoHeadphones,
  LogoBassDrop,
  LogoSamplePad,
  LogoCrossfader,
  LogoVinylCrate,
  LogoBPMCounter,
  LogoDualDeck,
  LogoTempoSlider,
  LogoUltimateTurntable,
  LogoCodeDeck,
  LogoSportsDJFusion,
  LogoBracketPlatter,
  LogoFullstackDJ,
  LogoVinylIDE,
  LogoChampionshipDeck,
  LogoControllerPro,
  LogoVinylSyntax,
  LogoGameDayMix,
} from '@/components/ui/Logo';
import { LogoSignature } from '@/components/ui/logo-new/LogoSignature';
import { LogoSignatureAlt } from '@/components/ui/logo-new/LogoSignatureAlt';
import { LogoMinimal, LogoMark as LogoMarkNew } from '@/components/ui/logo-new/LogoMinimal';
import { LogoTurntable } from '@/components/ui/logo-new/LogoTurntable';
import { LogoBridge } from '@/components/ui/logo-new/LogoBridge';

export type Category = 'all' | 'sports' | 'music' | 'tech' | 'bay-area';

export interface LogoConcept {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  Component: React.ComponentType<{ size?: number; className?: string }>;
  categories: Category[];
  tags: string[];
}

export const categories: { id: Category; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'sports', label: 'Sports' },
  { id: 'music', label: 'Music/DJ' },
  { id: 'tech', label: 'Tech' },
  { id: 'bay-area', label: 'Bay Area' },
];

export const logoConcepts: LogoConcept[] = [
  // SIGNATURE SERIES
  {
    id: 'signature',
    title: 'Signature',
    subtitle: 'Primary Brand Logo',
    description: 'Basketball-styled vinyl with football spindle. Code brackets as tonearms. Warriors left, 49ers right.',
    Component: LogoSignature,
    categories: ['sports', 'music', 'tech', 'bay-area'],
    tags: ['Primary', 'Hero', 'Recommended'],
  },
  {
    id: 'signature-alt',
    title: 'Signature Dark',
    subtitle: 'Professional Variant',
    description: 'Same concept, darker palette. Basketball vinyl with gold accents on dark background.',
    Component: LogoSignatureAlt,
    categories: ['sports', 'music', 'tech'],
    tags: ['Professional', 'Dark', 'Resume'],
  },
  {
    id: 'turntable',
    title: 'Turntable',
    subtitle: 'Full DJ Deck',
    description: 'Complete turntable with basketball vinyl platter, football label, and bracket tonearm.',
    Component: LogoTurntable,
    categories: ['music', 'tech'],
    tags: ['DJ', 'Equipment', 'Detailed'],
  },
  {
    id: 'bridge-new',
    title: 'Bay Bridge',
    subtitle: 'Bay Area Pride',
    description: 'Suspension bridge with basketball vinyl as setting sun. Towers in team colors.',
    Component: LogoBridge,
    categories: ['bay-area', 'sports'],
    tags: ['Local', 'SF', 'Bridge'],
  },
  {
    id: 'minimal-new',
    title: 'Minimal',
    subtitle: 'Small Sizes',
    description: 'Simplified for 24-40px. Football center, vinyl ring, team bracket colors.',
    Component: LogoMinimal,
    categories: ['tech'],
    tags: ['Small', 'Nav', 'Icon'],
  },
  {
    id: 'mark-new',
    title: 'Mark',
    subtitle: 'Favicon Size',
    description: 'Brackets + center dot only. For 16-24px spaces.',
    Component: LogoMarkNew,
    categories: ['tech'],
    tags: ['Favicon', 'Tiny', '16px'],
  },

  // LEGACY VARIANTS
  {
    id: 'base',
    title: 'Base Logo',
    subtitle: 'Default Mark',
    description: 'Simple code brackets with vinyl - the foundation of the brand.',
    Component: Logo,
    categories: ['tech'],
    tags: ['Default', 'Favicon', 'Simple'],
  },
  {
    id: 'professional',
    title: 'Professional',
    subtitle: 'Clean & Corporate',
    description: 'Minimal monochrome for resumes and business contexts.',
    Component: LogoProfessional,
    categories: ['tech'],
    tags: ['LinkedIn', 'Resume', 'Business'],
  },
  {
    id: 'creative',
    title: 'Creative',
    subtitle: 'Artistic & Expressive',
    description: 'Full color split - Warriors blue left, 49ers red right.',
    Component: LogoCreative,
    categories: ['sports', 'bay-area'],
    tags: ['Portfolio', 'Social', 'Merch'],
  },
  {
    id: 'basketball-vinyl',
    title: 'Basketball Vinyl',
    subtitle: 'Vinyl as Basketball',
    description: 'Basketball-styled vinyl with code brackets as DJ tonearms.',
    Component: LogoBasketballVinyl,
    categories: ['sports', 'music', 'tech'],
    tags: ['Signature', 'Unique'],
  },
  {
    id: 'streetwear',
    title: 'Streetwear',
    subtitle: 'Urban & Bold',
    description: '"AQ" graffiti style. A is gold, Q is red vinyl.',
    Component: LogoStreetwear,
    categories: ['music'],
    tags: ['Apparel', 'Stickers', 'DJ'],
  },
  {
    id: 'bridge-dj',
    title: 'Bridge + DJ',
    subtitle: 'Bay Area Meets Beats',
    description: 'Suspension bridge with vinyl record and tonearm.',
    Component: LogoBridgeDJ,
    categories: ['bay-area', 'music'],
    tags: ['Events', 'Local'],
  },
  {
    id: 'techy',
    title: 'Techy',
    subtitle: 'Digital & Futuristic',
    description: 'Circuit board aesthetic with hexagonal vinyl.',
    Component: LogoTechy,
    categories: ['tech'],
    tags: ['GitHub', 'Dev', 'Tech Talks'],
  },
  {
    id: 'sports-vinyl',
    title: 'Sports Vinyl',
    subtitle: 'All Elements Combined',
    description: 'Basketball, football, vinyl, tonearm, code brackets.',
    Component: LogoSportsVinyl,
    categories: ['sports', 'music', 'tech'],
    tags: ['Personal Brand', 'Versatile'],
  },
  {
    id: 'golden-gate',
    title: 'Golden Gate',
    subtitle: 'Iconic Minimal',
    description: 'International Orange bridge with subtle accents.',
    Component: LogoGoldenGateMinimal,
    categories: ['bay-area'],
    tags: ['SF', 'Classic', 'Local'],
  },
  {
    id: 'championship',
    title: 'Championship',
    subtitle: 'Ring Style',
    description: 'Sports championship ring with AQ monogram.',
    Component: LogoChampionshipRing,
    categories: ['sports'],
    tags: ['Prestige', 'Achievement'],
  },
  {
    id: 'neon-glow',
    title: 'Neon Glow',
    subtitle: 'Cyberpunk Vibes',
    description: 'Glowing neon effect with magenta and cyan accents.',
    Component: LogoNeonGlow,
    categories: ['tech', 'music'],
    tags: ['Night', 'Club', 'Cyber'],
  },
  {
    id: 'retro-80s',
    title: 'Retro 80s',
    subtitle: 'Synthwave Sunset',
    description: 'Synthwave aesthetic with sunset gradient and grid floor.',
    Component: LogoRetro80s,
    categories: ['music'],
    tags: ['Vintage', 'Synthwave', 'Retro'],
  },
  {
    id: 'geometric',
    title: 'Geometric',
    subtitle: 'Shapes & Lines',
    description: 'Clean geometric AQ letterforms with minimal accents.',
    Component: LogoGeometric,
    categories: ['tech'],
    tags: ['Minimal', 'Modern', 'Clean'],
  },
  {
    id: 'holographic',
    title: 'Holographic',
    subtitle: 'Iridescent Rainbow',
    description: 'Holographic gradient effect that shifts colors.',
    Component: LogoHolographic,
    categories: ['tech', 'music'],
    tags: ['Premium', 'Flashy', 'Modern'],
  },
  {
    id: 'sticker',
    title: 'Sticker',
    subtitle: 'Patch Style',
    description: 'Embroidered patch or die-cut sticker aesthetic.',
    Component: LogoSticker,
    categories: ['sports', 'bay-area'],
    tags: ['Merch', 'Sticker', 'Patch'],
  },
  {
    id: 'monogram-shield',
    title: 'Monogram Shield',
    subtitle: 'Classic Crest',
    description: 'Shield shape with AQ monogram, split team colors.',
    Component: LogoMonogramShield,
    categories: ['sports'],
    tags: ['Formal', 'Crest', 'Classic'],
  },
  {
    id: 'cassette',
    title: 'Cassette',
    subtitle: 'Retro Tape',
    description: 'Classic cassette tape with label and tape reels.',
    Component: LogoCassette,
    categories: ['music'],
    tags: ['Mixtape', 'Vintage', 'Audio'],
  },
  {
    id: 'waveform',
    title: 'Waveform',
    subtitle: 'Audio Visual',
    description: 'Audio waveform bars transitioning team colors.',
    Component: LogoWaveform,
    categories: ['music', 'tech'],
    tags: ['Audio', 'Beats', 'Sound'],
  },
  {
    id: 'pixel',
    title: 'Pixel Art',
    subtitle: '8-Bit Style',
    description: 'Retro 8-bit pixel art aesthetic.',
    Component: LogoPixel,
    categories: ['tech'],
    tags: ['Gaming', 'Retro', '8-Bit'],
  },
  {
    id: 'stamp',
    title: 'Wax Seal',
    subtitle: 'Official Stamp',
    description: 'Wax seal with wavy edges and AQ monogram.',
    Component: LogoStamp,
    categories: ['bay-area'],
    tags: ['Official', 'Seal', 'Premium'],
  },
  {
    id: 'blueprint',
    title: 'Blueprint',
    subtitle: 'Technical Schematic',
    description: 'Engineering blueprint style with dimensions.',
    Component: LogoBlueprint,
    categories: ['tech'],
    tags: ['Engineering', 'Technical', 'Dev'],
  },
  {
    id: 'mark',
    title: 'Logo Mark',
    subtitle: 'Minimal Icon',
    description: 'Smallest mark for tight spaces - just brackets and vinyl.',
    Component: LogoMark,
    categories: ['tech'],
    tags: ['Icon', 'Tiny', 'Favicon'],
  },
  {
    id: 'gradient-burst',
    title: 'Gradient Burst',
    subtitle: 'Radial Explosion',
    description: 'Radial gradient from gold to red to blue, vinyl grooves.',
    Component: LogoGradientBurst,
    categories: ['sports', 'music'],
    tags: ['Colorful', 'Dynamic', 'Bold'],
  },
  {
    id: 'outline',
    title: 'Outline',
    subtitle: 'Pure Linework',
    description: 'Minimal outline style - adapts to light/dark mode.',
    Component: LogoOutline,
    categories: ['tech'],
    tags: ['Minimal', 'Adaptive', 'Clean'],
  },
  {
    id: 'glitch',
    title: 'Glitch',
    subtitle: 'Digital Distortion',
    description: 'RGB offset glitch effect with scan lines.',
    Component: LogoGlitch,
    categories: ['tech', 'music'],
    tags: ['Cyber', 'Distorted', 'VHS'],
  },
  {
    id: 'jersey-number',
    title: 'Jersey',
    subtitle: 'Sports Uniform',
    description: 'Warriors jersey shape with number.',
    Component: LogoJerseyNumber,
    categories: ['sports'],
    tags: ['Uniform', 'Team', 'Athletic'],
  },
  {
    id: 'vinyl-only',
    title: 'Vinyl Record',
    subtitle: 'Pure Vinyl',
    description: 'Classic vinyl record with AQ label.',
    Component: LogoVinylOnly,
    categories: ['music'],
    tags: ['Record', 'Label', 'Classic'],
  },
  {
    id: 'terminal',
    title: 'Terminal',
    subtitle: 'Command Line',
    description: 'Terminal window with whoami command.',
    Component: LogoTerminal,
    categories: ['tech'],
    tags: ['CLI', 'Hacker', 'Dev'],
  },
  {
    id: 'hexagon',
    title: 'Hexagon',
    subtitle: 'Geometric Shape',
    description: 'Hexagonal frame with vinyl center.',
    Component: LogoHexagon,
    categories: ['tech'],
    tags: ['Geometric', 'Modern', 'Sharp'],
  },
  {
    id: 'sports-card',
    title: 'Sports Card',
    subtitle: 'Trading Card',
    description: 'Classic trading card format with stats.',
    Component: LogoSportsCard,
    categories: ['sports'],
    tags: ['Collectible', 'Card', 'Rookie'],
  },
  {
    id: 'coin',
    title: 'Gold Coin',
    subtitle: 'Medallion',
    description: 'Gold coin with embossed AQ monogram.',
    Component: LogoCoin,
    categories: ['sports', 'bay-area'],
    tags: ['Premium', 'Gold', 'Medal'],
  },
  {
    id: 'graffiti-tag',
    title: 'Graffiti Tag',
    subtitle: 'Street Art',
    description: 'Urban graffiti style AQ with drips.',
    Component: LogoGraffitiTag,
    categories: ['music', 'bay-area'],
    tags: ['Street', 'Urban', 'Tag'],
  },

  // DJ/MUSIC BEATS SERIES
  {
    id: 'dj-mixer',
    title: 'DJ Mixer',
    subtitle: 'Mixing Console',
    description: 'Channel faders, crossfader, and VU meters. Warriors/49ers split channels.',
    Component: LogoDJMixer,
    categories: ['music', 'tech'],
    tags: ['Mixer', 'Faders', 'DJ Gear'],
  },
  {
    id: 'beat-grid',
    title: 'Beat Grid',
    subtitle: 'Sequencer Style',
    description: '4x4 beat sequencer grid with team colors as active pads.',
    Component: LogoBeatGrid,
    categories: ['music', 'tech'],
    tags: ['MPC', 'Beats', 'Production'],
  },
  {
    id: 'frequency-spectrum',
    title: 'Frequency Spectrum',
    subtitle: 'Audio Analyzer',
    description: 'Frequency bars with gradient from blue to gold to red.',
    Component: LogoFrequencySpectrum,
    categories: ['music', 'tech'],
    tags: ['EQ', 'Spectrum', 'Audio'],
  },
  {
    id: 'turntable-platter',
    title: 'Turntable Platter',
    subtitle: 'Top-Down View',
    description: 'Spinning platter with speed indicator dots in team colors.',
    Component: LogoTurntablePlatter,
    categories: ['music'],
    tags: ['Platter', 'Spin', 'Technics'],
  },
  {
    id: 'cdj-display',
    title: 'CDJ Display',
    subtitle: 'Digital Player',
    description: 'CDJ screen with waveform, BPM display, and jog wheel.',
    Component: LogoCDJDisplay,
    categories: ['music', 'tech'],
    tags: ['CDJ', 'Pioneer', 'Digital'],
  },
  {
    id: 'scratch-pattern',
    title: 'Scratch Pattern',
    subtitle: 'Vinyl Scratches',
    description: 'Dynamic scratch marks suggesting vinyl manipulation.',
    Component: LogoScratchPattern,
    categories: ['music'],
    tags: ['Scratch', 'Turntablism', 'Skills'],
  },
  {
    id: 'soundwave-circle',
    title: 'Soundwave Circle',
    subtitle: 'Circular Audio',
    description: 'Oscilloscope-style circular soundwave pattern.',
    Component: LogoSoundwaveCircle,
    categories: ['music', 'tech'],
    tags: ['Oscilloscope', 'Wave', 'Audio'],
  },
  {
    id: 'headphones',
    title: 'Headphones',
    subtitle: 'DJ Cans',
    description: 'DJ headphones with Warriors/49ers colored ear cups.',
    Component: LogoHeadphones,
    categories: ['music'],
    tags: ['Headphones', 'Monitor', 'Audio'],
  },
  {
    id: 'bass-drop',
    title: 'Bass Drop',
    subtitle: 'Subwoofer Style',
    description: 'Speaker cone with bass vibration waves emanating.',
    Component: LogoBassDrop,
    categories: ['music'],
    tags: ['Bass', 'Speaker', 'Loud'],
  },
  {
    id: 'sample-pad',
    title: 'Sample Pad',
    subtitle: 'MPC Style',
    description: '4x4 drum machine pads with team colors pattern.',
    Component: LogoSamplePad,
    categories: ['music', 'tech'],
    tags: ['MPC', 'Samples', 'Drums'],
  },
  {
    id: 'crossfader',
    title: 'Crossfader',
    subtitle: 'Mix Control',
    description: 'Isolated crossfader with A/B channel markers.',
    Component: LogoCrossfader,
    categories: ['music'],
    tags: ['Crossfade', 'Mix', 'Transition'],
  },
  {
    id: 'vinyl-crate',
    title: 'Vinyl Crate',
    subtitle: 'Record Collection',
    description: 'Crate full of records with team-colored spines.',
    Component: LogoVinylCrate,
    categories: ['music'],
    tags: ['Crate', 'Collection', 'Digger'],
  },
  {
    id: 'bpm-counter',
    title: 'BPM Counter',
    subtitle: 'Tempo Display',
    description: 'Digital BPM readout with beat indicators.',
    Component: LogoBPMCounter,
    categories: ['music', 'tech'],
    tags: ['BPM', 'Tempo', 'Sync'],
  },
  {
    id: 'dual-deck',
    title: 'Dual Deck',
    subtitle: 'Two Turntables',
    description: 'Classic two turntables and a mixer setup.',
    Component: LogoDualDeck,
    categories: ['music'],
    tags: ['Setup', 'Decks', 'Classic'],
  },
  {
    id: 'tempo-slider',
    title: 'Tempo Slider',
    subtitle: 'Pitch Control',
    description: 'Pitch/tempo fader with percentage markings.',
    Component: LogoTempoSlider,
    categories: ['music', 'tech'],
    tags: ['Pitch', 'Tempo', 'Control'],
  },

  // ULTIMATE FUSION SERIES
  {
    id: 'ultimate-turntable',
    title: 'Ultimate Turntable',
    subtitle: 'All Elements Combined',
    description: 'Full DJ deck with basketball vinyl, football spindle, dual bracket tonearms, and waveform display. The complete fusion.',
    Component: LogoUltimateTurntable,
    categories: ['sports', 'music', 'tech'],
    tags: ['Ultimate', 'Fusion', 'Complete', 'Recommended'],
  },
  {
    id: 'code-deck',
    title: 'Code Deck',
    subtitle: 'Terminal + Turntable',
    description: 'Terminal window aesthetic with basketball vinyl inside. Bracket tonearms with tech-inspired accents.',
    Component: LogoCodeDeck,
    categories: ['tech', 'music', 'sports'],
    tags: ['Terminal', 'Tech', 'Developer'],
  },
  {
    id: 'sports-dj-fusion',
    title: 'Sports DJ Fusion',
    subtitle: 'Arena Scoreboard Style',
    description: 'Jumbotron aesthetic with basketball vinyl, football center, bold bracket tonearms, and LED display.',
    Component: LogoSportsDJFusion,
    categories: ['sports', 'music', 'tech'],
    tags: ['Arena', 'Scoreboard', 'Bold'],
  },
  {
    id: 'bracket-platter',
    title: 'Bracket Platter',
    subtitle: 'Bracket Grooves',
    description: 'Vinyl platter where the grooves are made of rotating brackets. Basketball surface with football label.',
    Component: LogoBracketPlatter,
    categories: ['tech', 'music', 'sports'],
    tags: ['Creative', 'Unique', 'Brackets'],
  },
  {
    id: 'fullstack-dj',
    title: 'Fullstack DJ',
    subtitle: 'Layered Stack',
    description: 'Three-layer design: brackets on top, basketball in middle, football at base. Visual hierarchy.',
    Component: LogoFullstackDJ,
    categories: ['tech', 'music', 'sports'],
    tags: ['Layers', 'Stack', 'Structure'],
  },
  {
    id: 'vinyl-ide',
    title: 'Vinyl IDE',
    subtitle: 'Editor Window Style',
    description: 'Editor window layout with sidebar, tabs, and basketball vinyl as the main visual. Bracket tonearms.',
    Component: LogoVinylIDE,
    categories: ['tech', 'music', 'sports'],
    tags: ['Window', 'Editor', 'Layout'],
  },
  {
    id: 'championship-deck',
    title: 'Championship Deck',
    subtitle: 'Ring + Turntable',
    description: 'Championship ring with basketball vinyl inside. Brackets as jeweled accents on sides.',
    Component: LogoChampionshipDeck,
    categories: ['sports', 'music', 'tech'],
    tags: ['Champion', 'Ring', 'Premium'],
  },
  {
    id: 'controller-pro',
    title: 'Controller Pro',
    subtitle: 'Full DJ Controller',
    description: 'Wide DJ controller with dual basketball jog wheels, mixer section, brackets, and display.',
    Component: LogoControllerPro,
    categories: ['music', 'sports', 'tech'],
    tags: ['Controller', 'Pioneer', 'Wide'],
  },
  {
    id: 'vinyl-syntax',
    title: 'Vinyl Syntax',
    subtitle: 'Colorful Label',
    description: 'Vinyl record with AQ monogram on basketball label. Color-coded decorative accents.',
    Component: LogoVinylSyntax,
    categories: ['tech', 'music', 'sports'],
    tags: ['Colorful', 'Label', 'Vibrant'],
  },
  {
    id: 'game-day-mix',
    title: 'Game Day Mix',
    subtitle: 'Stadium Atmosphere',
    description: 'Stadium lights and crowd silhouette with vinyl/basketball center. Game day energy.',
    Component: LogoGameDayMix,
    categories: ['sports', 'music', 'tech', 'bay-area'],
    tags: ['Stadium', 'GameDay', 'Hype'],
  },
];
